version: '3.9'

services:
  backend:
    build: .
    container_name: aspnet_backend
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend-network

networks:
  backend-network:
