name: Deploy app
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy
      run: |
          git pull
          docker compose down
          docker compose up -d --build
