name: Deploy app

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted  # указывает на self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Show directory contents (debug)
      run: ls -la

    - name: Deploy using Docker Compose
      run: |
        echo "▶ Переключаемся в директорию проекта"
        cd $GITHUB_WORKSPACE

        echo "▶ Проверяем наличие docker-compose.yml"
        ls -la

        echo "▶ Останавливаем текущие контейнеры"
        docker-compose down || true

        echo "▶ Скачиваем последние изменения (на всякий случай)"
        git pull origin master

        echo "▶ Запускаем контейнеры с пересборкой"
        docker-compose up -d --build